/* To Draw ERD diagram in MysqlWorkbench */

DROP DATABASE IF EXISTS fleet_management_erd;
CREATE DATABASE fleet_management_erd CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE fleet_management_erd;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS StatusHistories;
DROP TABLE IF EXISTS AuditLogs;
DROP TABLE IF EXISTS Expenses;
DROP TABLE IF EXISTS Incidents;
DROP TABLE IF EXISTS InventoryParts;
DROP TABLE IF EXISTS MaintenanceTickets;
DROP TABLE IF EXISTS Trips;
DROP TABLE IF EXISTS SupplierCodeOptions;
DROP TABLE IF EXISTS DocumentTypeCodeOptions;
DROP TABLE IF EXISTS MaintenanceTypeCodeOptions;
DROP TABLE IF EXISTS ExpenseTypeCodeOptions;
DROP TABLE IF EXISTS SeverityCodeOptions;
DROP TABLE IF EXISTS IncidentTypeCodeOptions;
DROP TABLE IF EXISTS TripPriorityCodeOptions;
DROP TABLE IF EXISTS StatusCodeOptions;
DROP TABLE IF EXISTS CargoTypeCodeOptions;
DROP TABLE IF EXISTS TripTypeCodeOptions;
DROP TABLE IF EXISTS Vehicles;
DROP TABLE IF EXISTS FuelTypeCodeOptions;
DROP TABLE IF EXISTS VehicleTypeCodeOptions;
DROP TABLE IF EXISTS LocationTypeCodeOptions;
DROP TABLE IF EXISTS LocationCodeOptions;
DROP TABLE IF EXISTS DepartmentCodeOptions;
DROP TABLE IF EXISTS RolePermissions;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS RoleMembers;
DROP TABLE IF EXISTS Roles;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE Roles (
  Id VARCHAR(80) NOT NULL,
  Code VARCHAR(20) NOT NULL,
  Name VARCHAR(120) NOT NULL,
  Description VARCHAR(500) NOT NULL DEFAULT '',
  Status VARCHAR(30) NOT NULL DEFAULT 'Active',
  IsDeleted INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  UNIQUE KEY UX_Roles_Code (Code)
) ENGINE=InnoDB;

CREATE TABLE RolePermissions (
  Id INT NOT NULL AUTO_INCREMENT,
  RoleId VARCHAR(80) NOT NULL,
  ModuleKey VARCHAR(80) NOT NULL,
  CanView BOOLEAN NOT NULL DEFAULT FALSE,
  CanCreate BOOLEAN NOT NULL DEFAULT FALSE,
  CanEdit BOOLEAN NOT NULL DEFAULT FALSE,
  CanDelete BOOLEAN NOT NULL DEFAULT FALSE,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  UNIQUE KEY UX_RolePermissions_RoleId_ModuleKey (RoleId, ModuleKey),
  CONSTRAINT FK_RolePermissions_Roles FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Users (
  Id VARCHAR(80) NOT NULL,
  Name VARCHAR(120) NOT NULL,
  EmployeeId VARCHAR(80) NOT NULL,
  NrcNumber VARCHAR(80) NOT NULL,
  Email VARCHAR(160) NOT NULL,
  PasswordHash VARCHAR(128) NOT NULL,
  RoleId VARCHAR(80) NOT NULL,
  Status VARCHAR(30) NOT NULL DEFAULT 'Active',
  Phone VARCHAR(40) NOT NULL DEFAULT '',
  Avatar VARCHAR(500) NOT NULL DEFAULT '',
  NrcFront VARCHAR(500) NOT NULL DEFAULT '',
  NrcBack VARCHAR(500) NOT NULL DEFAULT '',
  Department VARCHAR(120) NOT NULL DEFAULT '',
  Title VARCHAR(120) NOT NULL DEFAULT '',
  Location VARCHAR(120) NOT NULL DEFAULT '',
  Manager VARCHAR(120) NOT NULL DEFAULT '',
  LicenseNumber VARCHAR(80) NULL,
  LicenseClass VARCHAR(40) NULL,
  LicenseExpiry VARCHAR(40) NULL,
  EmergencyContactName VARCHAR(120) NOT NULL DEFAULT '',
  EmergencyContactRelation VARCHAR(80) NOT NULL DEFAULT '',
  EmergencyContactPhone VARCHAR(40) NOT NULL DEFAULT '',
  Address VARCHAR(255) NOT NULL DEFAULT '',
  TwoFactorEnabled BOOLEAN NOT NULL DEFAULT FALSE,
  Notes TEXT NULL,
  JoinDate VARCHAR(40) NOT NULL DEFAULT '',
  LastLogin VARCHAR(80) NULL,
  IsDeleted INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  KEY IX_Users_EmployeeId (EmployeeId),
  KEY IX_Users_Email (Email),
  KEY IX_Users_RoleId (RoleId),
  CONSTRAINT FK_Users_Roles FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE RoleMembers (
  Id VARCHAR(80) NOT NULL,
  RoleId VARCHAR(80) NOT NULL,
  RoleName VARCHAR(120) NOT NULL DEFAULT '',
  Name VARCHAR(120) NOT NULL DEFAULT '',
  Email VARCHAR(160) NOT NULL DEFAULT '',
  Phone VARCHAR(40) NOT NULL DEFAULT '',
  Status VARCHAR(30) NOT NULL DEFAULT 'Active',
  JoinDate VARCHAR(40) NOT NULL DEFAULT '',
  Avatar VARCHAR(500) NOT NULL DEFAULT '',
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  KEY IX_RoleMembers_RoleId (RoleId),
  CONSTRAINT FK_RoleMembers_Roles FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE DepartmentCodeOptions (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(120) NOT NULL,
  Description VARCHAR(500) NULL,
  Status VARCHAR(20) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UX_DepartmentCodeOptions_Name (Name)
) ENGINE=InnoDB;

CREATE TABLE LocationTypeCodeOptions (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(120) NOT NULL,
  Code VARCHAR(40) NOT NULL,
  Description VARCHAR(500) NULL,
  Status VARCHAR(20) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UX_LocationTypeCodeOptions_Name (Name),
  UNIQUE KEY UX_LocationTypeCodeOptions_Code (Code)
) ENGINE=InnoDB;

CREATE TABLE LocationCodeOptions (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(120) NOT NULL,
  Code VARCHAR(40) NOT NULL,
  Type VARCHAR(50) NOT NULL,
  Address VARCHAR(300) NOT NULL,
  City VARCHAR(120) NOT NULL,
  Country VARCHAR(120) NOT NULL,
  ContactPerson VARCHAR(120) NULL,
  Phone VARCHAR(40) NOT NULL,
  OperatingHours VARCHAR(80) NOT NULL,
  Notes VARCHAR(500) NULL,
  Status VARCHAR(20) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UX_LocationCodeOptions_Name (Name),
  UNIQUE KEY UX_LocationCodeOptions_Code (Code)
) ENGINE=InnoDB;

CREATE TABLE VehicleTypeCodeOptions (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(120) NOT NULL,
  Code VARCHAR(40) NOT NULL,
  Description VARCHAR(500) NULL,
  Status VARCHAR(20) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UX_VehicleTypeCodeOptions_Name (Name),
  UNIQUE KEY UX_VehicleTypeCodeOptions_Code (Code)
) ENGINE=InnoDB;

CREATE TABLE FuelTypeCodeOptions (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(120) NOT NULL,
  Code VARCHAR(40) NOT NULL,
  Description VARCHAR(500) NULL,
  Status VARCHAR(20) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UX_FuelTypeCodeOptions_Name (Name),
  UNIQUE KEY UX_FuelTypeCodeOptions_Code (Code)
) ENGINE=InnoDB;

CREATE TABLE Vehicles (
  Id VARCHAR(40) NOT NULL,
  Plate VARCHAR(40) NOT NULL,
  Region VARCHAR(120) NOT NULL,
  Type VARCHAR(120) NOT NULL,
  Model VARCHAR(120) NOT NULL,
  Make VARCHAR(120) NULL,
  Year VARCHAR(20) NULL,
  Color VARCHAR(80) NULL,
  Status VARCHAR(30) NOT NULL DEFAULT 'Active',
  Ownership VARCHAR(40) NULL,
  Driver VARCHAR(120) NOT NULL,
  DriverImage VARCHAR(500) NULL,
  Depot VARCHAR(120) NULL,
  Capacity VARCHAR(80) NULL,
  FuelCapacity VARCHAR(80) NULL,
  FuelType VARCHAR(80) NOT NULL,
  Vin VARCHAR(120) NULL,
  EngineNo VARCHAR(120) NULL,
  Odometer VARCHAR(80) NULL,
  LastService VARCHAR(40) NULL,
  NextService VARCHAR(40) NULL,
  ServiceNote VARCHAR(255) NULL,
  PurchaseCost VARCHAR(80) NULL,
  RegistrationNo VARCHAR(120) NULL,
  RegistrationExpiry VARCHAR(40) NULL,
  RoadTaxExpiry VARCHAR(40) NULL,
  InsuranceExpiry VARCHAR(40) NULL,
  InsuranceProvider VARCHAR(120) NULL,
  InsurancePolicy VARCHAR(120) NULL,
  InspectionDue VARCHAR(40) NULL,
  AcquiredDate VARCHAR(40) NULL,
  Image VARCHAR(500) NULL,
  IsDeleted INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  UNIQUE KEY UX_Vehicles_Plate (Plate)
) ENGINE=InnoDB;

-- Shared setup/code option table structure
CREATE TABLE TripTypeCodeOptions LIKE VehicleTypeCodeOptions;
CREATE TABLE CargoTypeCodeOptions LIKE VehicleTypeCodeOptions;
CREATE TABLE StatusCodeOptions LIKE VehicleTypeCodeOptions;
CREATE TABLE TripPriorityCodeOptions LIKE VehicleTypeCodeOptions;
CREATE TABLE IncidentTypeCodeOptions LIKE VehicleTypeCodeOptions;
CREATE TABLE SeverityCodeOptions LIKE VehicleTypeCodeOptions;
CREATE TABLE ExpenseTypeCodeOptions LIKE VehicleTypeCodeOptions;
CREATE TABLE MaintenanceTypeCodeOptions LIKE VehicleTypeCodeOptions;
CREATE TABLE DocumentTypeCodeOptions LIKE VehicleTypeCodeOptions;
CREATE TABLE SupplierCodeOptions LIKE VehicleTypeCodeOptions;

CREATE TABLE Trips (
  Id INT NOT NULL AUTO_INCREMENT,
  TripNumber VARCHAR(40) NOT NULL,
  TripType VARCHAR(80) NOT NULL,
  Status VARCHAR(40) NOT NULL,
  Priority VARCHAR(40) NOT NULL,
  CustomerName VARCHAR(160) NOT NULL,
  Department VARCHAR(120) NOT NULL,
  CostCenter VARCHAR(80) NULL,
  VehicleId VARCHAR(40) NOT NULL,
  VehiclePlate VARCHAR(40) NOT NULL,
  TrailerNumber VARCHAR(80) NULL,
  DriverName VARCHAR(120) NOT NULL,
  CoDriverName VARCHAR(120) NULL,
  DispatcherName VARCHAR(120) NOT NULL,
  CargoType VARCHAR(120) NOT NULL,
  LoadWeightKg DECIMAL(18,2) NOT NULL DEFAULT 0,
  LoadVolumeM3 DECIMAL(18,2) NOT NULL DEFAULT 0,
  PickupLocation VARCHAR(160) NOT NULL,
  DropoffLocation VARCHAR(160) NOT NULL,
  PickupContact VARCHAR(160) NULL,
  DropoffContact VARCHAR(160) NULL,
  DepartureDateTime VARCHAR(40) NOT NULL,
  EstimatedArrival VARCHAR(40) NOT NULL,
  ActualArrival VARCHAR(40) NULL,
  PlannedDistanceKm DECIMAL(18,2) NOT NULL DEFAULT 0,
  StartingOdometerKm DECIMAL(18,2) NOT NULL DEFAULT 0,
  CurrentOdometerKm DECIMAL(18,2) NOT NULL DEFAULT 0,
  EndingOdometerKm DECIMAL(18,2) NULL,
  FuelIssuedLiters DECIMAL(18,2) NOT NULL DEFAULT 0,
  TollEstimate DECIMAL(18,2) NOT NULL DEFAULT 0,
  PermitRequired BOOLEAN NOT NULL DEFAULT FALSE,
  TemperatureControlled BOOLEAN NOT NULL DEFAULT FALSE,
  TemperatureRange VARCHAR(80) NULL,
  SpecialInstructions TEXT NULL,
  DriverNotes TEXT NULL,
  IsDeleted INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  UNIQUE KEY UX_Trips_TripNumber (TripNumber),
  KEY IX_Trips_VehicleId (VehicleId),
  CONSTRAINT FK_Trips_Vehicles FOREIGN KEY (VehicleId) REFERENCES Vehicles(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE MaintenanceTickets (
  Id VARCHAR(40) NOT NULL,
  Vehicle VARCHAR(120) NOT NULL,
  VehicleId VARCHAR(40) NOT NULL,
  Issue VARCHAR(160) NOT NULL,
  Details VARCHAR(500) NOT NULL,
  ReportedDate VARCHAR(40) NOT NULL,
  Mechanic VARCHAR(120) NOT NULL,
  Status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  IsDeleted INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  KEY IX_MaintenanceTickets_VehicleId (VehicleId),
  CONSTRAINT FK_MaintenanceTickets_Vehicles FOREIGN KEY (VehicleId) REFERENCES Vehicles(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE InventoryParts (
  Id VARCHAR(40) NOT NULL,
  Name VARCHAR(160) NOT NULL,
  PartNo VARCHAR(80) NOT NULL,
  Category VARCHAR(120) NOT NULL,
  Stock INT NOT NULL DEFAULT 0,
  ReorderPoint INT NOT NULL DEFAULT 0,
  Supplier VARCHAR(160) NULL,
  UnitCost VARCHAR(80) NULL,
  Location VARCHAR(160) NULL,
  Image VARCHAR(500) NULL,
  IsDeleted INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  KEY IX_InventoryParts_PartNo (PartNo)
) ENGINE=InnoDB;

CREATE TABLE Incidents (
  Id VARCHAR(40) NOT NULL,
  VehicleId VARCHAR(40) NOT NULL,
  Driver VARCHAR(120) NOT NULL,
  Date VARCHAR(40) NOT NULL,
  Type VARCHAR(120) NOT NULL,
  Severity VARCHAR(40) NOT NULL,
  Status VARCHAR(40) NOT NULL,
  Cost VARCHAR(80) NULL,
  Notes TEXT NULL,
  IsDeleted INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  KEY IX_Incidents_VehicleId (VehicleId),
  CONSTRAINT FK_Incidents_Vehicles FOREIGN KEY (VehicleId) REFERENCES Vehicles(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE Expenses (
  Id INT NOT NULL AUTO_INCREMENT,
  ExpenseDate VARCHAR(40) NOT NULL,
  ExpenseType VARCHAR(120) NOT NULL,
  VehicleId VARCHAR(40) NULL,
  TripNumber VARCHAR(80) NULL,
  DriverName VARCHAR(120) NULL,
  Amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  Status VARCHAR(40) NOT NULL DEFAULT 'Active',
  Notes TEXT NULL,
  IsDeleted INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  KEY IX_Expenses_VehicleId (VehicleId),
  KEY IX_Expenses_TripNumber (TripNumber),
  CONSTRAINT FK_Expenses_Vehicles FOREIGN KEY (VehicleId) REFERENCES Vehicles(Id) ON DELETE SET NULL,
  CONSTRAINT FK_Expenses_Trips FOREIGN KEY (TripNumber) REFERENCES Trips(TripNumber) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE AuditLogs (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  RoleId VARCHAR(80) NOT NULL,
  ModuleKey VARCHAR(80) NOT NULL,
  Action VARCHAR(40) NOT NULL,
  EntityId VARCHAR(80) NOT NULL,
  Description TEXT NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  KEY IX_AuditLogs_RoleId (RoleId),
  CONSTRAINT FK_AuditLogs_Roles FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE StatusHistories (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  EntityType VARCHAR(80) NOT NULL,
  EntityId VARCHAR(80) NOT NULL,
  OldStatus VARCHAR(80) NULL,
  NewStatus VARCHAR(80) NOT NULL,
  RoleId VARCHAR(80) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  KEY IX_StatusHistories_RoleId (RoleId),
  KEY IX_StatusHistories_Entity (EntityType, EntityId),
  CONSTRAINT FK_StatusHistories_Roles FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

INSERT INTO Roles (Id, Code, Name, Description, Status) VALUES
('admin', 'ADMIN', 'Admin', 'System administrator role', 'Active'),
('dispatcher', 'DISPATCHER', 'Dispatcher', 'Trip dispatcher role', 'Active'),
('driver', 'DRIVER', 'Driver', 'Vehicle driver role', 'Active'),
('mechanic', 'MECHANIC', 'Mechanic', 'Maintenance mechanic role', 'Active');
